---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chutanku-whale
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-whale-app
      version: blue
  template:
    metadata:
      name: chutanku-whale-pod
      labels:
        app: hello-whale-app
        version: blue
    spec:
      containers:
      - name: hello-whale-container
        image: public.ecr.aws/f2c6u3p5/kkkkk:67
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: hello-whale-svc
  labels:
    app: hello-whale-app
spec:
  selector:
    app: hello-whale-app
    version: blue
  type: LoadBalancer
  ports:
#  - nodePort: 31113
    - port: 80
      targetPort: 80
